name: "Get Logs from SNEK"

on:
  workflow_dispatch:

jobs:
  get-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Get logs from docker
        uses: appleboy/ssh-action@master
        with:
          host: snekworld.org
          port: ${{ secrets.SSH_PORT_SNEK }}
          username: ${{ secrets.SSH_USERNAME_SNEK }}
          password: ${{ secrets.SSH_PASSWORD_SNEK }}
          script: |
            docker logs netrunner
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://snekworld.org
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
